name: GPU_CI_integration
on:
  schedule:
    # Run at 5:30 UTC every Monday
    - cron: '30 5 * * 1'
  workflow_dispatch:

jobs:
  start-aws-runner:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      mapping: ${{ steps.aws-start.outputs.mapping }}
      instances: ${{ steps.aws-start.outputs.instances }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GPU_SELF_HOSTED_ARN }}
          aws-region: us-east-1
      - name: Create cloud runner
        id: aws-start
        uses: omsf/start-aws-gha-runner@v1.0.0
        with:
          aws_image_id: ami-010e080c2b31bb75e
          aws_instance_type: g4dn.xlarge
          aws_home_dir: /home/ubuntu
          aws_root_device_size: 200
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
  self-hosted-test:
    runs-on: ${{ fromJSON(needs.start-aws-runner.outputs.instances) }} # This ensures that you only run on the instances you just provisioned
    needs:
      - start-aws-runner
    steps:
      - uses: actions/checkout@v4
      - name: Print disk usage
        run: "df -h"
      - name: Print Docker details
        run: "docker version || true"
      - uses: actions/checkout@v4

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a


      # More info on options: https://github.com/marketplace/actions/setup-micromamba
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: devtools/conda-envs/openadmet-models-gpu.yaml
          environment-name: openadmet-models
          condarc: |
            channels:
              - conda-forge

      - name: Install package
        # conda setup requires this special shell
        shell: bash -l {0}
        run: |
          python -m pip install . --no-deps
          micromamba list

      - name: Run GPU integration tests
        # conda setup requires this special shell
        shell: bash -l {0}
        # use the `-m gpu` marker to run only GPU tests
        run: |
          pytest -v -n auto -m gpu --cov=openadmet.models --cov-report=xml  --color=yes openadmet/models/tests/integration
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

      - name: Post to failure to Slack Channel
        if: ${{ failure() }}
        id: slack_failure
        uses: slackapi/slack-github-action@v2.1.1
        with:
            method: chat.postMessage
            token: ${{ secrets.SLACK_BOT_TOKEN }}
            payload: |
              channel: ${{ secrets.SLACK_CHANNEL }}
              text: "❌ *A GPU Integration Test Failed*\n*Repo:* ${{ github.repository }}\n*Run:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Logs>"

      - name: Post to success to Slack Channel
        if: ${{ success() }}
        id: slack_success
        uses: slackapi/slack-github-action@v2.1.1
        with:
            method: chat.postMessage
            token: ${{ secrets.SLACK_BOT_TOKEN }}
            payload: |
              channel: ${{ secrets.SLACK_CHANNEL }}
              text: "✅ *A GPU Integration Test Succeeded*\n*Repo:* ${{ github.repository }}\n*Run:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Results>"



  stop-aws-runner:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    needs:
      - start-aws-runner
      - self-hosted-test
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GPU_SELF_HOSTED_ARN }}
          aws-region: us-east-1
      - name: Stop instances
        uses: omsf/stop-aws-gha-runner@v1.0.0
        with:
          instance_mapping: ${{ needs.start-aws-runner.outputs.mapping }}
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
